export enum ESlobsEvent {
  LOAD = "slobs-load",
  UNLOAD = "slobs-unload",
  OPEN = "slobs-open",
  CLOSE = "slobs-close",
  ERROR = "slobs-error",
  COLLECTION_ADDED = "slobs-collection-added",
  COLLECTION_REMOVED = "slobs--collection-removed",
  COLLECTION_SWITCHED = "slobs-collection-switched",
  COLLECTION_UPDATED = "slobs-collection-updated",
  COLLECTION_WILLSWITCH = "slobs-collection-willswitch",
  ITEM_ADDED = "slobs-item-added",
  ITEM_REMOVED = "slobs-item-removed",
  ITEM_UPDATED = "slobs-item-updated",
  SCENE_ADDED = "slobs-scene-added",
  SCENE_REMOVED = "slobs-scene-removed",
  SCENE_SWITCHED = "slobs-scene-switched",
  SOURCE_ADDED = "slobs-source-added",
  SOURCE_REMOVED = "slobs-source-removed",
  SOURCE_UPDATED = "slobs-source-updated",
  RECORDING_STATUS_CHANGED = "slobs-recording-status-change",
  REPLAY_STATUS_CHANGED = "slobs-replay-status-change",
  STREAMING_STATUS_CHANGED = "slobs-streaming-status-change",
  STUDIOMODE_STATUS_CHANGED = "slobs-studiomode-status-change",
}
